{{- if and .Values.rbac.create .Values.rbac.useClusterRole -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "my-images.labels" . | nindent 4 }}
  name: {{ template "my-images.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "my-images.serviceAccountName" . }}
{{ include "my-images.namespace" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- if (not .Values.rbac.useExistingRole) }}
  name: {{ template "my-images.fullname" . }}
{{- else }}
  name: {{ .Values.rbac.useExistingRole }}
{{- end }}
{{- end }}