apiVersion: {{ template "cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ template "my-charts.fullname" . }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "my-charts.labels" . | nindent 12 }}
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          serviceAccountName: {{ include "my-charts.serviceAccountName" . }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ end }}
          initContainers:
            - name: kubexit
              image: cortexlabs/kubexit:0.40.0
              command: ['cp']
              args: ['/bin/kubexit', '/kubexit/kubexit']
              volumeMounts:
                - mountPath: /kubexit
                  name: kubexit
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ['/kubexit/kubexit', 'yarn']
              args: ['execute']
              env:
                - name: KUBEXIT_NAME
                  value: my-charts
                - name: KUBEXIT_GRAVEYARD
                  value: /graveyard
                - name: KUBEXIT_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: KUBEXIT_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: ACCESS_TYPE
                  value: {{ ternary "cluster" "namespace" .Values.rbac.useClusterRole }}
                - name: NAMESPACE
                  value: {{ .Release.Namespace }}
                - name: JUPITERONE_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ (tpl .Values.existingSecret.name .) | default (include "my-charts.fullname" .) }}
                      key: {{ .Values.existingSecret.jupiteroneAccountIdSecretKey | default "jupiteroneAccountId" }}
                - name: JUPITERONE_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ (tpl .Values.existingSecret.name .) | default (include "my-charts.fullname" .) }}
                      key: {{ .Values.existingSecret.jupiteroneApiKeySecretKey | default "jupiteroneApiKey" }}
                - name: JUPITERONE_API_BASE_URL
                  value: {{ template "settings.baseApiUrl" . }}
                - name: INTEGRATION_INSTANCE_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ (tpl .Values.existingSecret.name .) | default (include "my-charts.fullname" .) }}
                      key: {{ .Values.existingSecret.jupiteroneIntegrationInstanceIdSecretKey | default "jupiteroneIntegrationInstanceId" }}
                - name: LOAD_KUBERNETES_CONFIG_FROM_DEFAULT
                  value: 'false'