{{- if and .Values.rbac.create (eq .Values.rbac.useClusterRole false) (not .Values.rbac.useExistingRole) }}
{{- range $.Values.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "my-charts.fullname" . }}
  labels:
    {{- include "my-charts.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ''
    resources: ['*']
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - extensions
    resources: ['*']
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - apps
    resources: ['*']
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - batch
    resources: ['*']
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- end }}
