{{- if (not .Values.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-scripts.fullname" . }}
  labels:
    {{- include "argocd-scripts.labels" . | nindent 4 }}
type: Opaque
data:
  argoURL: {{ default "" .Values.secrets.argoURL | b64enc | quote }}
  argoUser: {{ default "" .Values.secrets.argoUser | b64enc | quote }}
  argoPassword: {{ default "" .Values.secrets.argoPassword | b64enc | quote }}
  jupiteroneAccountId: {{ default "" .Values.secrets.jupiteroneAccountId | b64enc | quote }}
  jupiteroneApiKey: {{ default "" .Values.secrets.jupiteroneApiKey | b64enc | quote }}
{{- end }}