{{- if (not .Values.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-integration-helm-charts.fullname" . }}
  labels:
    {{- include "argocd-integration-helm-charts.labels" . | nindent 4 }}
type: Opaque
data:
  jupiteroneAccountId: {{ default "" .Values.secrets.jupiteroneAccountId | b64enc | quote }}
  jupiteroneApiKey: {{ default "" .Values.secrets.jupiteroneApiKey | b64enc | quote }}
  jupiteroneIntegrationInstanceId: {{ default "" .Values.secrets.jupiteroneIntegrationInstanceId | b64enc | quote }}
{{- end }}